/*CREATE TABLE CDR*/
CREATE TABLE TB_CDR(
    DH_START_TIME			DATE,
	DH_END_TIME				DATE,
	NR_SUBSCRIBER_IP		VARCHAR(39),
	NM_USER_NAME			VARCHAR(50),
	NR_USER_CPF				VARCHAR(15),
	NM_CONTEXT_NAME     	VARCHAR(50),
	NR_MAC_ADDRESS			VARCHAR(50),
	NR_NAS_IP_ADDRESS		VARCHAR(39),
	NR_NET_DEVICE_OS		VARCHAR(39),
	NR_NET_DEVICE_BROWSER	VARCHAR(39),
	DH_REFERENCE_DATE		DATE,
	DS_REFERENCE_FILE		VARCHAR(80)
);

/*CREATE TABLE DHCP*/
CREATE TABLE TB_DHCP(
	DH_START_TIME			DATE,
	DH_END_TIME				DATE,
	NR_IP_ADDRESS			VARCHAR(39),
	NR_HW_ADDRESS			VARCHAR(39),
	DS_ACTION				VARCHAR(10),
	DS_PROTOCOL				VARCHAR(6),
	DH_REFERENCE_DATE		DATE,
	DS_REFERENCE_FILE		VARCHAR(80)
);

/*CREATE TABLE CGNAT*/
CREATE TABLE TB_DHCP(
	DH_START_TIME			DATE,
	DH_END_TIME				DATE,
	NR_ORIGIN_IP			VARCHAR(39),
	NR_ORIGIN_PORT			INT(10),
	NR_TRANSLATE_IP			VARCHAR(39),
	NR_TRANSLATE_PORT		INT(10),
	DH_REFERENCE_DATE		DATE,
	DS_REFERENCE_FILE		VARCHAR(80)
);

/*CREATE TABLE TBLOG*/
CREATE TABLE TB_LOG(
	DH_IMPORT_DATE			DATE,
	NM_FILE_NAME			VARCHAR(50),
	ST_STATUS				SMALLINT(1),
	DS_DESCRIPTION_ERROR    VARCHAR(100)
);
